site_name: Terraform Modules 

# theme:
#   name: material

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Terraform Modules: index.md
  - Application Service Module: application-service-module.md
  - Data Warehouse Module: data-warehouse-module.md
  - REST API Service Pattern: rest-api-service-pattern.md
  - User Authentication Service: user-authentication-service.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true