CREATE DATABASE IF NOT EXISTS ADMIN_DB; 
CREATE USER IF NOT EXISTS ADMIN_DB_USER_001 IDENTIFIED WITH sha256_password BY 'admindb001$:';
CREATE ROLE IF NOT EXISTS ADMIN_DB_ROLE;
GRANT SHOW, SELECT ON system.* TO ADMIN_DB_ROLE;
GRANT 
    SHOW, 
    SELECT, 
    INSERT,
    CREATE, 
    ALTER, 
    DROP 
    ON *.* TO ADMIN_DB_ROLE;
GRANT ADMIN_DB_ROLE TO ADMIN_DB_USER_001;