CREATE DATABASE IF NOT EXISTS DATA_EXPLORATION; 
CREATE USER IF NOT EXISTS DATA_EXPLORATION_USER_001 IDENTIFIED WITH sha256_password BY 'dataexplorationdb001$:';
CREATE ROLE IF NOT EXISTS DATA_EXPLORATION_ROLE;
GRANT 
    SELECT, 
    INSERT,
    CREATE, 
    ALTER, 
    DROP,
    SHOW 
    ON DATA_EXPLORATION.* TO DATA_EXPLORATION_ROLE;
GRANT DATA_EXPLORATION_ROLE TO DATA_EXPLORATION_USER_001;